# Generated by Django 6.0.3 on 2026-03-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('type', models.CharField(choices=[('MOVIE', 'Movie'), ('SHOW', 'Show')], max_length=10)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
