# Generated by Django 6.0.3 on 2026-03-31 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinetrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('show', 'Show')], max_length=10),
        ),
    ]
