# Generated by Django 6.0.3 on 2026-05-01 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinetrack", "0002_alter_title_name_alter_title_rating_alter_title_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="title",
            name="rating",
            field=models.IntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="release_year",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="title",
            name="type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("show", "Show")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
