# Generated by Django 6.0.3 on 2026-05-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinetrack", "0003_alter_title_name_alter_title_rating_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="title",
            index=models.Index(
                fields=["type", "release_year"], name="cinetrack_t_type_8ffa7a_idx"
            ),
        ),
    ]
